import type { Metadata } from "next";
import { JetBrains_Mono} from "next/font/google";
import "./globals.css";

const jetBrainsMonoSans = JetBrains_Mono({
  variable: "--font-jetbrains-mono-sans",
  subsets: ["latin"],
});

const jetBrainsMonoMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-none">
      <body
        className={`${jetBrainsMonoMono.variable} antialiased bg-dark font-mono scrollbar-none`}
      >
        {children} 
      </body>
    </html>
  );
}
